### ISSUE TITLE
Possible fix and suggestions

### ISSUE THREAD

**Issue by Nebelung-Dev** [Peridax/edpuzzleplus#10]
Fix: When you go to https://edpuzzle.com/api/v3/assignments/id it still works example: https://github.com/DylanBruner/edpuzzlehack/blob/main/cheat.js (this is a working cheat) if you remade the code it could still work!
suggestions: Make a bookmarklet (its like a extension but not blocked and easy to install, its a bookmark the runs javascript)
Add feedback: idk if this worked before but it would be a great feature

**Comment by Peridax** [comment]
I took a look at the API and it seems to not work the way the old one does. It doesn't show the correct answer until the user has submitted an answer for that question. They keep all the answers server-side and only reveal it to the user once the user has answered that question.

I appreciate you reaching out about this but I probably won't work on this again. Take care, God bless you.
